server:
  port: 7080
  
  
spring:
  application:
    name: reactive-book-client

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
